### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by sdwerwed** [fluent/fluent-plugin-opensearch#54]
(check apply)
- [x] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)
- [ ] (optional) already reported 3rd party upstream repository or mailing list if you use k8s addon or helm charts.

Error:
```
2022-05-21 00:16:02 +0000 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `+' for nil:NilClass"
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/excon-0.92.2/lib/excon/connection.rb:247:in `request'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `block in call'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.10.0/lib/faraday/adapter.rb:50:in `connection'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-excon-1.1.0/lib/faraday/adapter/excon.rb:31:in `call'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.10.0/lib/faraday/rack_builder.rb:154:in `build_response'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/faraday-1.10.0/lib/faraday/connection.rb:516:in `run_request'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-transport-1.0.0/lib/opensearch/transport/transport/http/faraday.rb:56:in `block in perform_request'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-transport-1.0.0/lib/opensearch/transport/transport/base.rb:297:in `perform_request'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-transport-1.0.0/lib/opensearch/transport/transport/http/faraday.rb:45:in `perform_request'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-transport-1.0.0/lib/opensearch/transport/client.rb:193:in `perform_request'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-ruby-1.0.0/lib/opensearch.rb:92:in `open_search_validation_request'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-ruby-1.0.0/lib/opensearch.rb:58:in `verify_open_search'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-ruby-1.0.0/lib/opensearch.rb:47:in `method_missing'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-api-1.0.0/lib/opensearch/api/namespace/common.rb:47:in `perform_request'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/opensearch-api-1.0.0/lib/opensearch/api/actions/indices/get_template.rb:57:in `get_template'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-opensearch-1.0.4/lib/fluent/plugin/opensearch_index_template.rb:52:in `template_exists?'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-opensearch-1.0.4/lib/fluent/plugin/opensearch_index_template.rb:115:in `template_install'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-opensearch-1.0.4/lib/fluent/plugin/opensearch_index_template.rb:142:in `block in templates_hash_install'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-opensearch-1.0.4/lib/fluent/plugin/opensearch_index_template.rb:141:in `each'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-opensearch-1.0.4/lib/fluent/plugin/opensearch_index_template.rb:141:in `templates_hash_install'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-opensearch-1.0.4/lib/fluent/plugin/out_opensearch.rb:324:in `block in configure'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-opensearch-1.0.4/lib/fluent/plugin/opensearch_index_template.rb:70:in `retry_operate'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluent-plugin-opensearch-1.0.4/lib/fluent/plugin/out_opensearch.rb:321:in `configure'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/plugin.rb:187:in `configure'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:132:in `add_match'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:74:in `block in configure'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:64:in `each'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/agent.rb:64:in `configure'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:149:in `configure'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/engine.rb:105:in `configure'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/engine.rb:80:in `run_configure'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:719:in `block in run_worker'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:971:in `main_process'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:711:in `run_worker'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/lib/fluent/command/fluentd.rb:376:in `<top (required)>'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/gems/fluentd-1.14.6/bin/fluentd:15:in `<top (required)>'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/bin/fluentd:23:in `load'
  2022-05-21 00:16:02 +0000 [error]: #0 /opt/bitnami/fluentd/bin/fluentd:23:in `<main>'
2022-05-21 00:16:02 +0000 [error]: Worker 0 finished unexpectedly with status 1
```

#### Steps to replicate

```
  <match fluent.**>
    @type null
  </match>
  <source>
    @type forward
    bind "0.0.0.0"
    port 24224
  </source>
  <source>
    @type http
    bind "0.0.0.0"
    port 9880
  </source>
  <filter **>
    @type dedot
    de_dot_nested true
    de_dot_separator "_"
  </filter>
  <filter kube.**>
    @type record_transformer
    enable_ruby true
    auto_typecast true
    <record>
      target_index logs-xxxx-dev-xxxx-xxxx-${if record["kubernetes_namespace_name"].include? "yy-" or record["kubernetes_namespace_name"].include? "zzz-" or record["kubernetes_namespace_name"].include? "ww-" or record["kubernetes_namespace_name"].include? "aaa-" then record ["kubernetes_namespace_name"] else "other" end;}-${Time.now.strftime("%Y-%m-%d");}
    </record>
    <record>
      region xxxx
    </record>
    <record>
      environment dev
    </record>
  </filter>
  <filter systemd.**>
    @type record_transformer
    enable_ruby true
    auto_typecast true
    <record>
      target_index logs-xxxx-dev-xxxx-xxxx-other-${Time.now.strftime("%Y-%m-%d");}
    </record>
    <record>
      region xxxx
    </record>
    <record>
      environment dev
    </record>
  </filter>
  <filter kube.**>
    @type prometheus
    <metric>
      name fluentd_kube_input_status_num_records_total
      type counter
      desc The total number of kubernetes incoming records
      <labels>
        namespace $.kubernetes_namespace_name
        container $.kubernetes_container_name
        hostname ${hostname}
      </labels>
    </metric>
  </filter>
  <filter systemd.**>
    @type prometheus
    <metric>
      name fluentd_systemd_input_status_num_records_total
      type counter
      desc The total number of systemd incoming records
      <labels>
        systemd_unit $._SYSTEMD_UNIT
        hostname $._HOSTNAME
        fluentd ${hostname}
        tag ${tag}
      </labels>
    </metric>
  </filter>
  <match fluentd.healthcheck>
    @type stdout
  </match>
  <match **>
    @log_level "info"
    @type opensearch
    host ""
    port 443
    user ""
    password xxxxxx
    include_timestamp true
    scheme https
    ssl_verify false
    ssl_version TLSv1_2
    id_key "_hash"
    index_date_pattern "now/d"
    target_index_key "target_index"
    index_name "logs-xxxx-dev-xxxx-xxxx-other-fallback"
    templates {"fluentd-logs-template":"/opt/bitnami/fluentd/conf/template.conf"}
    reload_connections false
    reconnect_on_error true
    reload_on_failure true
    log_os_400_reason true
    <buffer>
      @type "file"
      path "/opt/bitnami/fluentd/logs/buffers/"
      flush_thread_count 2
      flush_interval 10s
      chunk_limit_size 16m
      total_limit_size 60g
    </buffer>
  </match>
  <source>
    @type prometheus
    port 24231
  </source>
  <source>
    @type prometheus_monitor
    <labels>
      host ${hostname}
    </labels>
  </source>
  <source>
    @type prometheus_output_monitor
    <labels>
      host ${hostname}
    </labels>
  </source>
```

#### Expected Behavior or What you need to ask

To show at least what is the error, or what is missing.

#### Using Fluentd and OpenSearch plugin versions

* OS version
* Bare Metal or within Docker or Kubernetes or others? AKS
* Fluentd v1.0 or later
  * paste result of ``fluentd --version`` or ``td-agent --version``
```
activesupport (7.0.2.3)
addressable (2.8.0)
aws-eventstream (1.2.0)
aws-partitions (1.579.0)
aws-sdk-core (3.130.2)
aws-sdk-kms (1.56.0)
aws-sdk-s3 (1.113.1)
aws-sdk-sqs (1.51.0)
aws-sigv4 (1.5.0)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
bundler (2.3.12, 2.3.11)
cgi (default: 0.1.0.1)
concurrent-ruby (1.1.10)
cool.io (1.7.1)
csv (default: 3.1.2)
date (default: 3.0.3)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
digest-crc (0.6.4)
domain_name (0.5.20190701)
elastic-transport (8.0.0)
elasticsearch (8.1.2)
elasticsearch-api (8.1.2)
elasticsearch-xpack (7.17.1)
etc (default: 1.1.0)
excon (0.92.2)
faraday (1.10.0)
faraday-em_http (1.0.0)
faraday-em_synchrony (1.0.0)
faraday-excon (1.1.0)
faraday-httpclient (1.0.1)
faraday-multipart (1.0.3)
faraday-net_http (1.0.1)
faraday-net_http_persistent (1.2.0)
faraday-patron (1.0.0)
faraday-rack (1.0.0)
faraday-retry (1.0.3)
faraday_middleware-aws-sigv4 (0.6.1)
fcntl (default: 1.0.0)
ffi (1.15.5)
ffi-compiler (1.0.1)
fiddle (default: 1.0.0)
fileutils (default: 1.4.1)
fluent-config-regexp-type (1.0.0)
fluent-plugin-concat (2.5.0)
fluent-plugin-dedot_filter (1.0.0)
fluent-plugin-detect-exceptions (0.0.14)
fluent-plugin-elasticsearch (5.2.2)
fluent-plugin-grafana-loki (1.2.18)
fluent-plugin-kafka (0.17.5)
fluent-plugin-kubernetes_metadata_filter (2.10.0)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-opensearch (1.0.4)
fluent-plugin-prometheus (2.0.2)
fluent-plugin-record-modifier (2.1.0)
fluent-plugin-rewrite-tag-filter (2.4.0)
fluent-plugin-s3 (1.6.1)
fluent-plugin-systemd (1.0.5)
fluentd (1.14.6)
forwardable (default: 1.3.1)
getoptlong (default: 0.1.0)
http (4.4.1)
http-accept (1.7.0)
http-cookie (1.0.4)
http-form_data (2.3.0)
http-parser (1.2.3)
http_parser.rb (0.8.0)
i18n (1.10.0)
io-console (default: 0.5.6)
ipaddr (default: 1.2.2)
irb (default: 1.2.6)
jmespath (1.6.1)
json (default: 2.3.0, 2.1.0)
jsonpath (1.1.2)
kubeclient (4.9.3)
logger (default: 1.4.2)
lru_redux (1.1.0)
ltsv (0.1.2)
matrix (default: 0.2.0)
mime-types (3.4.1)
mime-types-data (3.2022.0105)
minitest (5.15.0, 5.13.0)
msgpack (1.5.1)
multi_json (1.15.0)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.2.0)
netrc (0.11.0)
observer (default: 0.1.0)
oj (3.3.10)
open3 (default: 0.1.0)
opensearch-api (1.0.0)
opensearch-ruby (1.0.0)
opensearch-transport (1.0.0)
openssl (default: 2.1.3)
ostruct (default: 0.2.0)
power_assert (1.1.7)
prime (default: 0.1.1)
prometheus-client (4.0.0)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.7)
racc (default: 1.4.16)
rake (13.0.6, 13.0.1)
rdoc (default: 6.2.1.1)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
recursive-open-struct (1.1.3)
reline (default: 0.1.5)
rest-client (2.1.0)
rexml (default: 3.2.3.1)
rss (default: 0.2.8)
ruby-kafka (1.4.0)
ruby2_keywords (0.0.5)
rubygems-update (3.3.11)
sdbm (default: 1.0.0)
serverengine (2.2.5)
sigdump (0.2.4)
singleton (default: 0.1.0)
stringio (default: 0.1.0)
strptime (0.2.5)
strscan (default: 1.0.3)
systemd-journal (1.4.2)
test-unit (3.3.4)
timeout (default: 0.1.0)
tracer (default: 0.1.0)
tzinfo (2.0.4)
tzinfo-data (1.2022.1)
unf (0.1.4)
unf_ext (0.0.8.1)
uri (default: 0.10.0)
webrick (1.7.0, default: 1.6.1)
xmlrpc (0.3.0)
yajl-ruby (1.4.2)
yaml (default: 0.1.0)
zlib (default: 1.1.0)
```
* OpenSearch plugin version
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
* OpenSearch version (optional) 
* OpenSearch template(s) (optional)

**Comment by sdwerwed** [comment]
It was a new breaking change in the helm chart, `ExtraEnv` to `ExtraEnvVars`, and environment variables were missing for host and password configuration. I think we can close this, or add a better error for the required variables.
