### ISSUE TITLE
Plugin not compatible with fluentd 1.15.2

### ISSUE THREAD

**Issue by bloodguard** [fluent/fluent-plugin-opensearch#73]
(check apply)
- [X ] read [the contribution guideline](https://github.com/fluent/fluent-plugin-opensearch/blob/master/CONTRIBUTING.md)
#### Steps to replicate

Use this image from docker hub:
fluent/fluentd:v1.15.2-1.0

Install the following plugins:

RUN ["gem", "install","fluent-plugin-opensearch", "-v", "1.0.8"]
RUN ["gem", "install", "fluent-plugin-prometheus", "--no-document", "--version", "2.0.3"]
RUN ["gem","install","fluent-plugin-record-modifier", "--no-document","--version","2.1.0"]

Have a config that contains an opensearch match
You will get the following error:
```
2022-08-25 19:34:36 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2022-08-25 19:34:36 +0000 [info]: gem 'fluentd' version '1.15.2'
2022-08-25 19:34:36 +0000 [info]: gem 'fluent-plugin-opensearch' version '1.0.8'
2022-08-25 19:34:36 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.3'
2022-08-25 19:34:36 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2022-08-25 19:34:36 +0000 [debug]: adding store type="opensearch"
/usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core/xml/parser.rb:74:in `set_default_engine': Unable to find a compatible xml library. Ensure that you have installed or added to your Gemfile one of ox, oga, libxml, nokogiri or rexml (RuntimeError)
from /usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core/xml/parser.rb:96:in `<class:Parser>'
from /usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core/xml/parser.rb:7:in `<module:Xml>'
from /usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core/xml/parser.rb:5:in `<module:Aws>'
from /usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core/xml/parser.rb:3:in `<top (required)>'
from /usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core/xml.rb:8:in `require_relative'
from /usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core/xml.rb:8:in `<top (required)>'
from /usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core.rb:77:in `require_relative'
from /usr/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.135.0/lib/aws-sdk-core.rb:77:in `<top (required)>'
from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-opensearch-1.0.8/lib/fluent/plugin/out_opensearch.rb:57:in `<top (required)>'
from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/registry.rb:103:in `block in search'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/registry.rb:100:in `each'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/registry.rb:100:in `search'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/registry.rb:44:in `lookup'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin.rb:169:in `new_impl'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin.rb:114:in `new_output'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/multi_output.rb:108:in `block in configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/multi_output.rb:99:in `each'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/multi_output.rb:99:in `configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/out_copy.rb:39:in `configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin.rb:187:in `configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/agent.rb:132:in `add_match'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/agent.rb:74:in `block in configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/agent.rb:64:in `each'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/agent.rb:64:in `configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/label.rb:31:in `configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:146:in `block in configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:146:in `each'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/root_agent.rb:146:in `configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/engine.rb:105:in `configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/engine.rb:80:in `run_configure'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/supervisor.rb:712:in `run_supervisor'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/bin/fluentd:15:in `<top (required)>'
from /usr/bin/fluentd:25:in `load'
from /usr/bin/fluentd:25:in `<main>'
```
#### Expected Behavior or What you need to ask

Simply have the plugin work normally. Was working fine with version 1.14.5

#### Using Fluentd and OpenSearch plugin versions

* OS version: 1.3
* Bare Metal or within Docker or Kubernetes or others? : with Docker/Kubernetes
* Fluentd version: 1.15.2
* OpenSearch plugin version: 1.0.8

**Comment by cosmo0920** [comment]
This is not caused by Fluentd's compatibilities.
The root cause of this issue is upgraded core component that is Ruby on Fluentd docker image.

After releasing Fluentd v1.15 image, we start to use Ruby 3 or later on our Fluentd official image.

So, you have to install rexml or nokogiri as a XML parser library like as:

```dockerfile
RUN ["gem", "install","rexml", "-v", "3.2.5"]
```

**Comment by bloodguard** [comment]
@cosmo0920  Hello ! Sorry for the delayed response.

I tried and it works ! Thanks for the answer. Although, this bring another question. Why is no XML library not included in the plugin since its necessary with fluentd 1.15 ? If you want to let the user choose, why not mention in the documentation its necessary ? (maybe i missed it).

Thank you.

**Comment by cosmo0920** [comment]
> I tried and it works ! Thanks for the answer. Although, this bring another question. Why is no XML library not included in the plugin since its necessary with fluentd 1.15 ?

I’m glad to hear that. We had decided to upgrade Ruby version from 2.7 to 3.1. This causes the lack of XML related operation gem from fluentd docker image. Sorry for the inconvenience.
We have to bundle some of XML library by default on our official Fluentd image.

**Comment by cosmo0920** [comment]
Then, this issue should be tracking by https://github.com/fluent/fluentd-docker-image/issues/344.
This is not OpenSearch plugin issue but our official base image issue. Thanks for your report.
