### ISSUE TITLE
Problem refreshing AWS credentials after a while (out_opensearch_expire_credentials timer detached)

### ISSUE THREAD

**Issue by salavessa** [fluent/fluent-plugin-opensearch#74]
There seems to be an issue refreshing AWS credentials where after a while (could be hours/days or more) an error happens (```[error]: #0 Unexpected error raised. Stopping the timer. title=:out_opensearch_expire_credentials error_class=Aws::Errors::MissingCredentialsError error="unable to sign request without credentials set"``` + ```[error]: #0 Timer detached. title=:out_opensearch_expire_credentials```) and after around 1 hour (probably the token duration time) it starts failing to push the logs to OpenSearch with messages like ```[warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2022-08-26 05:32:20 +0000 chunk="5e71e374ec40ad1da90069a1909c0e63" error_class=Fluent::Plugin::OpenSearchOutput::RecoverableRequestFailure error="could not push logs to OpenSearch cluster ({:host=>\"<AWS_OPENSEARCH_1_3>.<region>.es.amazonaws.com\", :port=>443, :scheme=>\"https\"}): [403] {\"message\":\"The security token included in the request is expired\"}"```
Full log in attached [opensearch-issue.log](https://github.com/fluent/fluent-plugin-opensearch/files/9433964/opensearch-issue.log) file.

#### Steps to replicate

Unable to replicate, it just happens after some time (hours/days/...).

#### Expected Behavior or What you need to ask

Ability to recover from the error, or have logic where the doesn't happen in the first place.

#### Using Fluentd and OpenSearch plugin versions

* OS version: Ubuntu 20.04
* Bare Metal or within Docker or Kubernetes or others? Kubernetes
* Fluentd v1.0 or later
  * td-agent 4.4.1 fluentd 1.15.2 (c32842297ed2c306f1b841a8f6e55bdd0f1cb27f)
* OpenSearch plugin version
  * fluent-plugin-opensearch version 1.0.7
* OpenSearch version (optional): AWS OpenSearch 1.3
* OpenSearch template(s) (optional)

**Comment by amontalban** [comment]
We had a somewhat similar error running `fluent/fluentd-kubernetes-daemonset:v1.14.6-debian-opensearch-1.1` image.

```
2022-09-28 17:23:16 +0000 [error]: #0 [opensearch] Unexpected error raised. Stopping the timer. title=:out_opensearch_expire_credentials error_class=Aws::STS::Errors::InvalidIdentityToken error="Couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements"  ```

Not sure if we can somehow configure it to retry. Maybe we can use `unrecoverable_error_types`?

**Comment by salavessa** [comment]
Maybe this can help further investigation - servers are also experiencing other type of error (`error_class=Seahorse::Client::NetworkingError`) which causes `Timer detached. title=:out_opensearch_expire_credentials` and auth failure around an hour after due to `The security token included in the request is expired`:
```
2022-11-02 12:36:08 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:out_opensearch_expire_credentials error_class=Seahorse::Client::NetworkingError error="execution expired"
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/net/http.rb:960:in `open'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/net/http.rb:958:in `connect'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/net/http.rb:938:in `start'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/delegate.rb:83:in `method_missing'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/net_http/connection_pool.rb:307:in `start_session'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/net_http/connection_pool.rb:100:in `session_for'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/net_http/handler.rb:128:in `session'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/net_http/handler.rb:76:in `transmit'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/net_http/handler.rb:50:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/plugins/content_length.rb:24:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/plugins/request_callback.rb:85:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/xml/error_handler.rb:10:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/signature_v4.rb:58:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/http_checksum.rb:19:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/checksum_algorithm.rb:136:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/query/handler.rb:30:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/recursion_detection.rb:18:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/endpoint_discovery.rb:80:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/plugins/response_target.rb:24:in `call'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/seahorse/client/request.rb:72:in `send_request'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-sts/client.rb:825:in `assume_role'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/assume_role_credentials.rb:65:in `refresh'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/refreshing_credentials.rb:30:in `initialize'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.131.3/lib/aws-sdk-core/assume_role_credentials.rb:53:in `initialize'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:236:in `new'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:236:in `aws_credentials'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:351:in `block (2 levels) in configure'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:349:in `synchronize'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:349:in `block in configure'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2022-11-02 12:36:08 +0000 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-11-02 12:36:08 +0000 [error]: #0 Timer detached. title=:out_opensearch_expire_credentials
[...]
2022-11-02 13:41:36 +0000 [info]: #0 disable filter chain optimization because [Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method.
The client is unable to verify distribution due to security privileges on the server side. Some functionality may not be compatible if the server is running an unsupported product.
2022-11-02 13:42:38 +0000 [warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2022-11-02 13:43:09 +0000 chunk="5ec7cffe03353c38c2f086a96ce4ed44" error_class=Fluent::Plugin::OpenSearchOutput::RecoverableRequestFailure error="could not push logs to OpenSearch cluster ({:host=>\"search-atom-logs-szwnz6wiusktpyvhlbuuxenfxq.eu-west-1.es.amazonaws.com\", :port=>443, :scheme=>\"https\"}): [403] {\"message\":\"The security token included in the request is expired\"}"
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:1133:in `rescue in send_bulk'
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:1095:in `send_bulk'
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:906:in `block in write'
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:905:in `each'
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-opensearch-1.0.7/lib/fluent/plugin/out_opensearch.rb:905:in `write'
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:1180:in `try_flush'
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'
  2022-11-02 13:42:38 +0000 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by cosmo0920** [comment]
Is this patch https://github.com/fluent/fluent-plugin-opensearch/pull/78/files effective to reduce you all’s issue?

**Comment by salavessa** [comment]
Hi @cosmo0920,

I wouldn't say #78 will be effctive as, from my understanding of the actual problem based in the logs, the isue is not arount the refresh time, it's around the timer responsible to refresh the credentials being detached/terminated (`[error]: #0 Timer detached. title=:out_opensearch_expire_credentials`) and consequently credentials not getting "refreshed" ever again, so the current ones will expire at some point independently of the `refresh_credentials_interval` value introduced in #78 (as there's no timer to refresh them).

So I think the only thing that would actually be required to fix this is a retry mechanism to get a new set of temporary credentials when those fail to refresh (instead of detaching the timer and never refreshing again) as the underlying errors observed so far (`Aws::Errors::MissingCredentialsError error="unable to sign request without credentials set"` and `Seahorse::Client::NetworkingError`) seem to be related to temporary AWS failures (API and network).

**Comment by cosmo0920** [comment]
Hmm, I see. We have to investigate further to handle "accurate" understanding for this issue. 🤔

**Comment by LeonD9** [comment]
Hey @cosmo0920 ,
Any news regarding this issue? it still continues to happen and the pod remains in running state (I am using this image:  v1.15.1-debian-opensearch-1.1) so it takes time to know logs aren't being sent, any way to do health check for this plugin so it will restart the pod if this issue happens?

**Comment by Jonniedev** [comment]
I think setting `refresh_credentials_interval` definitely helps.

But the underlying issue might be: [Aws::AssumeRoleCredentials.new(...)](https://github.com/fluent/fluent-plugin-opensearch/blob/main/lib/fluent/plugin/out_opensearch.rb#LL238C27-L238C57)

I think we should set `duration_seconds` parameter (see [AssumeRoleCredentials docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/AssumeRoleCredentials.html)).

**Comment by LeonD9** [comment]
@Jonniedev I think it does help since this issue only happens every few months after I set `refresh_credentials_interval` to `1h`, but it still happens, would be great if it happened and it caused the pod to restart and not continue running with the problem.

**Comment by cosmo0920** [comment]
Could this patch https://github.com/fluent/fluent-plugin-opensearch/pull/78 work for you all?

**Comment by Jonniedev** [comment]
Thanks very much!
This looks fine, but needs extensive testing.
Also, I think it shows conflicts at the moment.

**Comment by cosmo0920** [comment]
Oh, you're right. I updated the PR to resolve conflicts.
Would you mind if you tried the patch?
